spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: bxm1014
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

jwt:
  secret: 24dab312-0824-4c19-b053-c02b34ad4437
  expiration: 999999
